# Generated by Django 6.0.6 on 2026-06-15 13:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('receipt', 'Receipt'), ('travel_advisory', 'Travel Advisory')], max_length=20)),
                ('file', models.FileField(blank=True, null=True, upload_to='documents/')),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='bookings.booking')),
            ],
            options={
                'ordering': ['-generated_at'],
            },
        ),
    ]
